### ISSUE TITLE
Consider to use VCR.py to record HTTP interactions during testing

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-py#105]
For an overview and details on VCR.py see [here](https://vcrpy.readthedocs.io/en/latest/index.html).

OQT uses this library to record all interactions with the ohsome API. For an example see [here](https://github.com/GIScience/ohsome-quality-analyst/blob/main/workers/tests/integrationtests/test_ohsome_client.py).

I happy to discuss this in person.

**Comment by SlowMo24** [comment]
implemented in https://github.com/GIScience/ohsome-py/commit/a6365b01ad59605b2ada1a6def47bbac8d260ce8 ff. Thanks for sharing!
