### ISSUE TITLE
Add citation suggestion to README

### ISSUE THREAD

**Issue by redfrexx** [GIScience/ohsome-py#122]
Add a suggestion on how to cite the ohsome-py package to the README.md

**Comment by SlowMo24** [comment]
@rp280 please first have a look at our other public software like OSHDB to see how they do it. If nothing fits for our case, have a look how one can generally cite software. Then add a suggestion of how one should cite ohsome-py in to the `README` in a new branch with a MR.

/cc @tyrasd and @joker234
