### ISSUE TITLE
[Feature request] Automatically record debug info

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-py#32]
I havn't seen any logging in the code (that might be a good idea?) but for simple bug/issue-tracking and to share queries with others (e.g. your ohsome buddy) it would be helpful to automatically save the request that was issued. The format might need to be discussed with the ohsome team. Currently we mostly create curl request that imitate the python requests.

If

- the response !=200 or
- the code is terminated by the user

the response (if any), the endpoint, the body and, if applicable, the bpolys geojson may be saved to e.g. `./` or `/tmp` to easily reassess what happened.

**Comment by redfrexx** [comment]
Thanks, yes this is a very good point, which should be improved. So far the user has to do the error handling themselves by catching the `OhsomeException` error which has a `to_json()` method to write the error along with the query parameters to file. Handling this through logging would be more convenient.

**Comment by SlowMo24** [comment]
I have not checked i your code but this is how I had to handle the error response from requests (though this is not very safe as it raises an error during error handling):

```
response=requests.post(URL, data=body)
    try:
        response.raise_for_status()
    except HTTPError as e:
        if response.text:
            raise HTTPError('{} Error Message: {}'.format(str(e), response.text))
        else:
           raise e
```
Some way of how requests is implemented prevents it from printing the error message if the error is directly raised. There are some issues and feature requests to improve this in the github of the requests package but it seemed like it wont happen.

**Comment by redfrexx** [comment]
I've implemented a first solution for automatically logging ohsome error messages. It can be enabled/disabled when the `OhsomeClient` instance is created e.g. if `OhsomeClient(log=True)` ohsome errors will be writting to a new json file in the folder `./ohsome_log`. An `OhsomeException` will always be raised no matter whether`log=True` or `log=False`. It's possible to change the log folder when creating the client, e.g. `OhsomeClient(log_dir="some/other/path")`. The log file looks like this for example

``` json
{
    "timestamp": "2021-02-19T09:59:00.085447",
    "status": 413,
    "message": "The given query is too large in respect to the given timeout. Please use a smaller region and/or coarser time period.",
    "requestUrl": "https://api.ohsome.org/v1/elements/geometry",
    "parameters": {
        "bboxes": "8.497689,49.296019,8.899145,49.517938",
        "filter": "landuse=forest or natural=wood or natural=tree or natural=tree_row",
        "timeout": 0.01,
        "properties": "tags"
    }
}
```
So is this kind of what you had in mind?

**Comment by redfrexx** [comment]
> I have not checked i your code but this is how I had to handle the error response from requests (though this is not very safe as it raises an error during error handling):
> 
> ```
> response=requests.post(URL, data=body)
> try:
>     response.raise_for_status()
> except HTTPError as e:
>     if response.text:
>         raise HTTPError('{} Error Message: {}'.format(str(e), response.text))
>     else:
>        raise e
> ```
> 
> Some way of how requests is implemented prevents it from printing the error message if the error is directly raised. There are some issues and feature requests to improve this in the github of the requests package but it seemed like it wont happen.

Thanks for pointing out this issue! I've made the error handling a bit more specific (see below). This way all general errors (e.g. connection errors) and ohsome API specific errors are caught and reported. I'm just not sure yet whether the `ValueError` is handled correctly, if an invalid json file is received from the ohsome API, because I don't have a test case for that yet. But besides that this setup is working with my test cases. Do you think this will catch all the errors you are getting as well? If not, can you provide an example query, where it doesn't work?

https://github.com/GIScience/ohsome-py/blob/d0ea2cfaee3626d564831dd164b51e286ff40f16/ohsome/client.py#L210-L254

**Comment by SlowMo24** [comment]
I cannot test this right now but will keep this in mind when encountering issues.
