### ISSUE TITLE
Implement API-Endpoints for API v1

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/ohsome-py#4]
- [x] Metadata
- [x] Data Extraction
- [x] Data aggregation (tbd)

**Comment by redfrexx** [comment]
Endpoints to query metadata have been added to `OhsomeClient`. See #14. 
New properties of OhsomeClient: `start_timestamp`, `end_timestamp`, `api_version` and `metadata`.

**Comment by redfrexx** [comment]
All components of the ohsome endpoints (e.g. elements, count, groupBy, boundary) have been added as methods to `OhsomeClient` class so code completion can be used. Still this does not make sure that only valid endpoint urls are created.

**Comment by redfrexx** [comment]
I've implemented subclasses for `OhsomeClient` which make sure that only methods are available which lead to valid endpoints. See issue #22.
