### ISSUE TITLE
Add dependencies to README

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-py#54]
It may be a good idea to list the dependencies of this package in the README.

**Comment by SlowMo24** [comment]
which according to `pip show ohsome` are 

`Requires: geopandas, numpy, pip, pyproj, multidict, pandas, requests`

Also with conda you possibly want to install these first before running `pip install ohsome --no-deps`

**Comment by redfrexx** [comment]
Yes, good point. I'll add it to the README.
