### ISSUE TITLE
log file naming not robust

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-py#55]
Having the error code in the log file name creates the following issues

- files are no longer ordered in the file tree but rather grouped by error code
- error codes like the following create 'invalid' filenames: 
![grafik](https://user-images.githubusercontent.com/12476914/116564832-9c786a80-a905-11eb-81d7-2930928e7135.png)

**Comment by redfrexx** [comment]
ok, thanks! Will fix it asap.

**Comment by SlowMo24** [comment]
yes, thats what I would suggest. the file is unique anyway with the timestamp.
