### ISSUE TITLE
remove duplicate / after api-base url

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-py#57]
ohsome-py will combine the base-url (https://api.ohsome.org/v1) with the endpoint using a `//`: `https://api.ohsome.org/v1//elements/count/groupBy/boundary`. While this may not cause any harm (https://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything  @joker234 ?) it might be better style to not do this.

**Comment by joker234** [comment]
You shouldn't normally do that as it is looking “unclean”. But yes, in reality it *often* doesn't cause any harm. I would suggest to use tools to properly combine your paths to a URL.

In Python, I think there are some functions in `urllib.parse` or `pathlib` which might come in handy for that.

see also the other responses to the stackoverflow question you posted.
