### ISSUE TITLE
Remove the version cap of geopandas

### ISSUE THREAD

**Issue by tqa236** [GIScience/ohsome-py#97]
Hello, 

Thanks a lot for this great package. 

I just have a little trouble installing the package due to a version conflict, can someone help me out, please?

The requirement in my code is `geopandas>=0.10.2`, I suppose it is compatible with `ohsome` since it's mentioned in Readme that `ohsome` supports `geopandas>=0.9.0`

But when I install the package, `geopandas` is capped to `0.9.0`, which creates a requirement conflict for me.

```
(from fiona>=1.8->geopandas<0.10.0,>=0.9.0->ohsome)
```

Do you know if it is possible to remove the version cap of `geopandas` in `ohsome`? Or is there any workaround for this error?

**Comment by redfrexx** [comment]
Thanks for reporting! I'm having a look at it.

**Comment by redfrexx** [comment]
Hi @tqa236, I've published a new version on pypi today which should work with geopandas ^0.10.0. If you still have problems, reopen the issue.
